version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: ["air"]
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      PORT: "8080"
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_ICON_EMOJI: ${SLACK_ICON_EMOJI}
      SLACK_USERNAME: ${SLACK_USERNAME}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /go${APP_PATH}
    working_dir: /go${APP_PATH}
